version: 1.0.{build}
os:
- WMF 5

clone_folder: c:\projects\PackageManagementProviderResource
install:
- ps: cinst -y pester
build_script:

- ps: Copy-Item -Recurse "c:\projects\PackageManagementProviderResource\" "$Env:ProgramFiles\WindowsPowerShell\Modules\" -Force -Verbose

    & "c:\projects\PackageManagementProviderResource\Test\run-tests.ps1"
